Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$src='C:\Stage3-Work\source-current'
$cpPath='C:\Stage3-Work\state\stage3-verification-checkpoint.json'
$provPath='C:\Stage3-Work\state\stage3-authentic-020-fixture-provenance.json'
$archive='D:\rasoathopdong-v0.4.0-phase1-final-closed-r13.zip'
$fixture='C:\Stage3-Work\fixtures\stage2-runtime-authentic\catalog-0.2.0-schema3'
$expectedArchiveSha='9eff2eebdfbb2f4fe786a6443606f9d1fb136293db89bae02199445848e2e39b'
Set-Location -LiteralPath $src
$head=(git rev-parse HEAD).Trim()
$branch=(git branch --show-current).Trim()
$status=@(git status --porcelain)
if($head -ne '550510636c212c8b77e29ff2434317e566d66fe9'){ throw "Unexpected source HEAD $head" }
if($status.Count -ne 0){ throw "Current source worktree not clean: $($status -join '; ')" }
$diff=@(git diff --name-only stage3-baseline-v0.4.0..HEAD | ForEach-Object { $_.Trim() } | Where-Object { $_ })
$expectedDiff=@('tests/RasoatHopDong.Tests/Stage7InstallerContractTests.cs','tests/RasoatHopDong.Tests/Stage7PublishContractTests.cs')
if((Compare-Object ($diff | Sort-Object) ($expectedDiff | Sort-Object)).Count -ne 0){ throw "Unexpected baseline diff: $($diff -join ',')" }
$archiveSha=(Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash.ToLowerInvariant()
if($archiveSha -ne $expectedArchiveSha){ throw 'Authentic archive hash mismatch' }
if(-not(Test-Path -LiteralPath (Join-Path $fixture 'appdata.sqlite')) -or -not(Test-Path -LiteralPath (Join-Path $fixture 'fixture-manifest.json'))){ throw 'Authentic fixture missing' }
$provSha=(Get-FileHash -LiteralPath $provPath -Algorithm SHA256).Hash.ToLowerInvariant()
$fixtureHashes=[ordered]@{}
Get-ChildItem -LiteralPath $fixture -File | Sort-Object Name | ForEach-Object { $fixtureHashes[$_.Name]=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant() }
$cp=Get-Content -LiteralPath $cpPath -Raw | ConvertFrom-Json
$cp.recordedAtUtc=[DateTime]::UtcNow.ToString('o')
$cp.source.worktreeClean=$true
$cp.source.head=$head
$cp.source.branch=$branch
$cp.verification | Add-Member -NotePropertyName migration020To030Authentic -NotePropertyValue 'PASS; authentic Phase1 0.2.0/DB3/map2 fixture; Stage2PostPromotionRuntimeGateTests 11/11 Debug + 11/11 Release; 0 failed; 0 skipped' -Force
$m=$cp.migration020To030
$m.status='PASS'
$m.archiveFoundOnStage3=$true
$m | Add-Member -NotePropertyName actualArchivePath -NotePropertyValue $archive -Force
$m | Add-Member -NotePropertyName actualArchiveSha256 -NotePropertyValue $archiveSha -Force
$m | Add-Member -NotePropertyName authenticHistoricalSourceRoot -NotePropertyValue 'C:\Stage3-Work\historical\phase1-final-closed-r13\rasoathopdong-v0.4.0-phase1-final-closed-r13' -Force
$m | Add-Member -NotePropertyName authenticHistoricalSourceContract -NotePropertyValue ([pscustomobject]@{appVersion='0.4.0';engineVersion='0.3.0';criteriaCatalogVersion='0.2.0';databaseSchemaVersion='3';criteriaSnapshotSchemaVersion='4';officialCriteriaCatalogSchemaVersion='2';officialCriteriaCatalogManifestSchemaVersion='2';criteriaCatalogMigrationMapSchemaVersion='2'}) -Force
$m | Add-Member -NotePropertyName fixtureRoot -NotePropertyValue $fixture -Force
$m | Add-Member -NotePropertyName fixtureProvenanceSha256 -NotePropertyValue $provSha -Force
$m | Add-Member -NotePropertyName fixtureFileSha256 -NotePropertyValue ([pscustomobject]$fixtureHashes) -Force
$m | Add-Member -NotePropertyName preparationEvidence -NotePropertyValue '1/1 PASS Release; preparation harness compiled against authentic Phase1 production source; only test harness and frozen Phase2 test inputs injected into a separate copy' -Force
$m | Add-Member -NotePropertyName postPromotionEvidence -NotePropertyValue 'Stage2PostPromotionRuntimeGateTests: 11/11 PASS Debug and 11/11 PASS Release using authentic fixture' -Force
$m.syntheticFixtureAllowed=$false
$m.reason='Authentic Phase1 archive was found on D: with exact expected SHA-256. Fixture was generated by authentic 0.2.0/DB3/map2 production code in an isolated harness copy, then migrated and verified by current 0.3.0 code in Debug and Release.'
$c=$cp.closure
$c.stage3FullyClosed=$false
$c.onlyOpenGate=$null
$c | Add-Member -NotePropertyName earlySensitiveVerificationCompleted -NotePropertyValue $true -Force
$c | Add-Member -NotePropertyName earlySensitiveVerificationStatus -NotePropertyValue 'PASS' -Force
$c | Add-Member -NotePropertyName stage3OverallStatus -NotePropertyValue 'IN_PROGRESS' -Force
$c | Add-Member -NotePropertyName remainingStage3Scope -NotePropertyValue '784 real-contract corpus defect discovery/holdout/regression, full Review+Compare real-data validation, compatibility continuation as needed, and final production cohort/benchmark/Windows acceptance/release gates.' -Force
$tmp=$cpPath+'.tmp'
$cp | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $tmp -Encoding UTF8
Move-Item -LiteralPath $tmp -Destination $cpPath -Force
$cpSha=(Get-FileHash -LiteralPath $cpPath -Algorithm SHA256).Hash.ToLowerInvariant()
$early=[ordered]@{
 schemaVersion=1; recordedAtUtc=[DateTime]::UtcNow.ToString('o'); status='PASS';
 sourceHead=$head; sourceWorktreeClean=$true; productionPatchApplied=$false; userFacingUiChanged=$false;
 authenticArchivePath=$archive; authenticArchiveSha256=$archiveSha;
 authenticSourceContract=[ordered]@{appVersion='0.4.0';engineVersion='0.3.0';criteriaCatalogVersion='0.2.0';databaseSchemaVersion='3';criteriaCatalogMigrationMapSchemaVersion='2'};
 fixtureRoot=$fixture; fixtureProvenanceSha256=$provSha; fixtureFiles=$fixtureHashes;
 fixturePreparation='1/1 PASS Release against authentic Phase1 production source';
 currentPostPromotionDebug='11/11 PASS; 0 failed; 0 skipped'; currentPostPromotionRelease='11/11 PASS; 0 failed; 0 skipped';
 previousFullRegression='2197/2197 PASS Debug + 2197/2197 PASS Release; no production source changes since';
 earlySensitiveVerificationCompleted=$true; stage3FullyClosed=$false;
 remainingStage3Scope='784 real-contract corpus and final release gates'
}
$earlyPath='C:\Stage3-Work\state\stage3-early-sensitive-closure.json'
$early | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $earlyPath -Encoding UTF8
$earlySha=(Get-FileHash -LiteralPath $earlyPath -Algorithm SHA256).Hash.ToLowerInvariant()
Write-Output "SOURCE_HEAD=$head"
Write-Output "SOURCE_WORKTREE_CLEAN=True"
Write-Output "BASELINE_DIFF=$($diff -join ',')"
Write-Output "CHECKPOINT_SHA256=$cpSha"
Write-Output "EARLY_CLOSURE_SHA256=$earlySha"
Write-Output "PROVENANCE_SHA256=$provSha"
Write-Output 'STAGE3_EARLY_SENSITIVE_VERIFICATION=PASS'
Write-Output 'STAGE3_OVERALL=IN_PROGRESS'